secrets: secretfile.yml
tasks:
  task-a:
    rss:  http://showrss.info/rss.php?user_id={{ secrets.showrss.ano }}&hd=null&proper=1&raw=true&magnets=false
    all_series: yes
    thetvdb_lookup: yes
    pathscrub: windows
    set:
      magnets: no
      skip_files:
        - '*.nfo'
        - '*.sfv'
        - '*[sS]ample*'
        - '*.txt'
    transmission:
      host: localhost
      port: 9091
      username: '{{ secrets.transmission.username }}'
      password: '{{ secrets.transmission.password }}'
      main_file_only: true
      content_filename: '{{ tvdb_series_name }} - {{ tvdb_season }}x{{ tvdb_episode|pad(2) }} - {{ tvdb_ep_name|default('''') }}'
      path: /mnt/hdd/media/Video/TV/{{series_name}}/Season {{series_season}}
      addpaused: no
    email:
      template: html
      from: RasPi
      subject: Shows Ready to Watch
      to:
        - '{{ secrets.gmail.to }}'
        - '{{ secrets.gmail.to2 }}'
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_login: True
      smtp_username: '{{ secrets.gmail.user }}'
      smtp_password: '{{ secrets.gmail.password }}'
      smtp_tls: true

