tasks:
  # downloading task
  download-rss:
    rss:  http://showrss.info/rss.php?user_id=147166&hd=null&proper=1&raw=true
    # fetch all the feed series
    all_series: yes
    # use deluge to download the torrents
    deluge:
      path: /mnt/hdd/deluge/incomplete
      movedone: /mnt/hdd/deluge/flexget/{{series_name}}/
      main_file_only: yes
      keep_subs: yes
  # sorting task
  sort-files:
    find:
      # directory with the files to be sorted
      path: /mnt/hdd/deluge/flexget/
      # fetch all avi, mkv and mp4 files, skips the .part files (unfinished torrents)
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    seen: local
    # this is needed for the episode names
    thetvdb_lookup: yes
    all_series:
      # all_series rejects all episodes here, even with seen: local, so parse_only must be added
      parse_only: yes
    # TVDB doesn't recognise every show so you must add those here manually
   # series:
    #  - Agents of S.H.I.E.L.D.
    move:
      # this is where the series will be stored
      to: /mnt/hdd/media/Video/TV/{{ series_name }}/Season {{ series_season }}
      # save the file as "Series Name - SxxEyy - Episode Name.ext"
      filename: '{{ series_name }} - {{ series_id }} - {{ tvdb_ep_name|default(False) }}{{ location | pathext }}'
      clean_source: 100    

    # Send an email
    email:
      template: html
      from: RasPi
      subject: Shows Ready to Watch
      to:
        - acordill@gmail.com
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_login: True
      smtp_username: rs9642@gmail.com
      smtp_password: radio1
      smtp_tls: true
